from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon, QFont, QCursor

from src.common.widgets.lineedit.zvilineedits import ButtonLineEdit
from src.util.zviutil import getResource
from src.common.widgets.label.zvilabels import LinkLabel

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("ZVI Login")
        Dialog.resize(419, 239)
        Dialog.setStyleSheet("")
        Dialog.setWindowIcon(QIcon(getResource("zvilogo.ico")))
        Dialog.setWindowOpacity(200.0)
        Dialog.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.signupButton = LinkLabel(Dialog)
        self.signupButton.setMaximumWidth(85)
        self.signupButton.setStyleSheet("color: rgb(0, 145, 245);")
        self.signupButton.setObjectName("signupButton")
        self.signupButton.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayout.addWidget(self.signupButton, 7, 1, 1, 1)
        self.passwordEdit = ButtonLineEdit(getResource("show.png"), Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordEdit.sizePolicy().hasHeightForWidth())
        self.passwordEdit.setSizePolicy(sizePolicy)
        self.passwordEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.passwordEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("color: rgb(0, 145, 245);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.usernameEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameEdit.sizePolicy().hasHeightForWidth())
        self.usernameEdit.setSizePolicy(sizePolicy)
        self.usernameEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.usernameEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.usernameEdit.setObjectName("usernameEdit")
        self.gridLayout.addWidget(self.usernameEdit, 0, 0, 1, 2)
        self.forgotButton = LinkLabel(Dialog)
        font = QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.forgotButton.setFont(font)
        self.forgotButton.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.forgotButton.setStyleSheet("color: rgb(0, 145, 245);")
        self.forgotButton.setObjectName("forgotButton")
        self.forgotButton.setMaximumHeight(20)
        self.gridLayout.addWidget(self.forgotButton, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.loginButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loginButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.loginButton.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setFlat(False)
        self.loginButton.setObjectName("loginButton")
        self.rememberMe = QtWidgets.QCheckBox(Dialog)
        self.rememberMe.setObjectName("rememberMe")
        self.gridLayout.addWidget(self.rememberMe, 2, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.loginButton, 4, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.usernameEdit, self.passwordEdit)
        Dialog.setTabOrder(self.passwordEdit, self.rememberMe)
        Dialog.setTabOrder(self.rememberMe, self.loginButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ZVI Login"))
        self.signupButton.setText(_translate("Dialog", "Sign up"))
        self.passwordEdit.setPlaceholderText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "Don\'t have an account?"))
        self.usernameEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.forgotButton.setText(_translate("Dialog", "Forgot Password?"))
        self.loginButton.setText(_translate("Dialog", "Login"))
        self.rememberMe.setText(_translate("Dialog", "Remember Me"))
