from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
from src.util.zviutil import getResource


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QIcon(getResource("zvilogo.ico")))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setActivationOrder(QtWidgets.QMdiArea.StackingOrder)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.actionView = QtWidgets.QMenu(self.menuView)
        self.actionView.setObjectName("actionView")
        self.menuShow = QtWidgets.QMenu(self.actionView)
        self.menuShow.setObjectName("menuShow")
        self.menuProgramsExcel = QtWidgets.QMenu(self.menuView)
        self.menuProgramsExcel.setObjectName("menuPrograms_Excel")
        self.menuPrograms = QtWidgets.QMenu(self.menuProgramsExcel)
        self.menuPrograms.setObjectName("menuPrograms")
        self.menuExcel = QtWidgets.QMenu(self.menuProgramsExcel)
        self.menuExcel.setObjectName("menuExcel")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuVersion = QtWidgets.QMenu(self.menuHelp)
        self.menuVersion.setObjectName("menuUpdate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMSA = QtWidgets.QAction(MainWindow)
        self.actionMSA.setObjectName("actionMSA")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        self.actionCascade.setObjectName("actionCascade")
        self.actionTile = QtWidgets.QAction(MainWindow)
        self.actionTile.setObjectName("actionTile")
        self.actionCloseAll = QtWidgets.QAction(MainWindow)
        self.actionCloseAll.setObjectName("actionClose_All")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport_A_Bug")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionVersion")
        self.actionMS = QtWidgets.QAction(MainWindow)
        self.actionMS.setObjectName("actionMS")
        self.actionVS = QtWidgets.QAction(MainWindow)
        self.actionVS.setObjectName("actionVS")
        self.actionMP = QtWidgets.QAction(MainWindow)
        self.actionMP.setObjectName("actionModule_Program")
        self.actionshowHW = QtWidgets.QAction(MainWindow)
        self.actionshowHW.setObjectName("actionshowHW")
        self.actionshowVS = QtWidgets.QAction(MainWindow)
        self.actionshowVS.setObjectName("actionshowVS")
        self.actionshowMS = QtWidgets.QAction(MainWindow)
        self.actionshowMS.setObjectName("actionshowMS")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionLogOut = QtWidgets.QAction(MainWindow)
        self.actionLogOut.setObjectName("actionLogOut")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLogOut)
        self.menuFile.addAction(self.actionExit)
        self.menuShow.addAction(self.actionshowHW)
        self.menuShow.addAction(self.actionshowVS)
        self.menuShow.addAction(self.actionshowMS)
        self.actionView.addAction(self.menuShow.menuAction())
        self.actionView.addSeparator()
        self.actionView.addAction(self.actionCascade)
        self.actionView.addAction(self.actionTile)
        self.actionView.addSeparator()
        self.actionView.addAction(self.actionCloseAll)
        self.menuPrograms.addAction(self.actionMS)
        self.menuPrograms.addAction(self.actionVS)
        self.menuPrograms.addAction(self.actionMP)
        self.menuExcel.addAction(self.actionMSA)
        self.menuProgramsExcel.addAction(self.menuExcel.menuAction())
        self.menuProgramsExcel.addSeparator()
        self.menuProgramsExcel.addAction(self.menuPrograms.menuAction())
        
        self.menuView.addAction(self.actionView.menuAction())
        self.menuView.addAction(self.menuProgramsExcel.menuAction())
        self.menuVersion.addAction(self.actionUpdate)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionReport)
        self.menuHelp.addAction(self.menuVersion.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZVI"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionView.setTitle(_translate("MainWindow", "Window View"))
        self.menuShow.setTitle(_translate("MainWindow", "Show"))
        self.menuProgramsExcel.setTitle(_translate("MainWindow", "Programs/Excel"))
        self.menuPrograms.setTitle(_translate("MainWindow", "Programs"))
        self.menuExcel.setTitle(_translate("MainWindow", "Excel"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuVersion.setTitle(_translate("MainWindow", "Version"))
        self.actionMSA.setText(_translate("MainWindow", "MSA"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCascade.setText(_translate("MainWindow", "Cascade"))
        self.actionTile.setText(_translate("MainWindow", "Tile"))
        self.actionCloseAll.setText(_translate("MainWindow", "Close All"))
        self.actionHelp.setText(_translate("MainWindow", "ZVIApp Help"))
        self.actionReport.setText(_translate("MainWindow", "Report a Bug..."))
        self.actionUpdate.setText(_translate("MainWindow", "Check for updates..."))
        self.actionMS.setText(_translate("MainWindow", "MS"))
        self.actionVS.setText(_translate("MainWindow", "VVS"))
        self.actionMP.setText(_translate("MainWindow", "Module Program"))
        self.actionshowHW.setText(_translate("MainWindow", "Home Window"))
        self.actionshowVS.setText(_translate("MainWindow", "VS"))
        self.actionshowMS.setText(_translate("MainWindow", "MS"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionLogOut.setText(_translate("MainWindow", "Logout..."))
