from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QFont


class Ui_signUp(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("signup")
        Dialog.resize(380, 270)
        Dialog.setMinimumSize(QtCore.QSize(380, 270))
        Dialog.setMaximumSize(QtCore.QSize(380, 280))
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(-1, 0, 331, 201))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 315, 230))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 35))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.usernameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usernameEdit.setMinimumSize(QtCore.QSize(120, 20))
        self.usernameEdit.setMaximumSize(QtCore.QSize(120, 20))
        self.usernameEdit.setObjectName("username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passwordEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordEdit.setMinimumSize(QtCore.QSize(120, 20))
        self.passwordEdit.setMaximumSize(QtCore.QSize(120, 20))
        self.passwordEdit.setObjectName("password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.emailEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.emailEdit.setMinimumSize(QtCore.QSize(150, 20))
        self.emailEdit.setMaximumSize(QtCore.QSize(150, 20))
        self.emailEdit.setObjectName("email")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.emailEdit)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.workstationEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.workstationEdit.setMinimumSize(QtCore.QSize(120, 20))
        self.workstationEdit.setMaximumSize(QtCore.QSize(120, 20))
        self.workstationEdit.setText("")
        self.workstationEdit.setObjectName("workstation")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.workstationEdit)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.valveSizingEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.valveSizingEdit.setMinimumSize(QtCore.QSize(120, 20))
        self.valveSizingEdit.setMaximumSize(QtCore.QSize(150, 20))
        self.valveSizingEdit.setObjectName("valvesizing location")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.valveSizingEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.signupButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.signupButton.setFont(font)
        self.signupButton.setObjectName("signup_btn")
        self.verticalLayout.addWidget(self.signupButton)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Account Setup"))
        self.label_4.setText(_translate("Dialog", "ZVI Account Setup"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">Username:</span><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">Password:</span><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Email:"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">Workstation #:</span><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.workstationEdit.setPlaceholderText(_translate("Dialog", "ZVIWS[#]"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" text-decoration: underline;\">ValveSizing Directory:</span><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.valveSizingEdit.setPlaceholderText(_translate("Dialog", "Paste path here."))
        self.signupButton.setText(_translate("Dialog", "Create Account"))

