from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtGui import QIcon

from src.util.zviutil import getResource


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(643, 482)
        Settings.setWindowIcon(QIcon(getResource("settings.ico")))
        Settings.setMinimumSize(QtCore.QSize(0, 182))
        Settings.setMaximumSize(QtCore.QSize(20000, 20000))
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget()
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("directory")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.workingDirectoryListWidget = QtWidgets.QListWidget(self.tab)
        self.workingDirectoryListWidget.setObjectName("wd_listwidget")
        self.verticalLayout.addWidget(self.workingDirectoryListWidget)
        self.previousWorkingDirectoryButton = QtWidgets.QPushButton(self.tab)
        self.previousWorkingDirectoryButton.setObjectName("wd_previousButton")
        self.verticalLayout.addWidget(self.previousWorkingDirectoryButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.workingDirectoryEdit = QtWidgets.QLineEdit(self.tab)
        self.workingDirectoryEdit.setText("")
        self.workingDirectoryEdit.setReadOnly(True)
        self.workingDirectoryEdit.setObjectName("workingDirectoryEdit")
        self.horizontalLayout_2.addWidget(self.workingDirectoryEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.workingDirectoryButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workingDirectoryButton.sizePolicy().hasHeightForWidth())
        self.workingDirectoryButton.setSizePolicy(sizePolicy)
        self.workingDirectoryButton.setObjectName("WorkingDirectoryButton")
        self.verticalLayout.addWidget(self.workingDirectoryButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.valveSizingListWidget = QtWidgets.QListWidget(self.tab)
        self.valveSizingListWidget.setObjectName("vs_listwidget")
        self.verticalLayout_2.addWidget(self.valveSizingListWidget)
        self.previousValveSizingButton = QtWidgets.QPushButton(self.tab)
        self.previousValveSizingButton.setObjectName("vs_previousButton")
        self.verticalLayout_2.addWidget(self.previousValveSizingButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.valveSizingDirectoryEdit = QtWidgets.QLineEdit(self.tab)
        self.valveSizingDirectoryEdit.setText("")
        self.valveSizingDirectoryEdit.setReadOnly(True)
        self.valveSizingDirectoryEdit.setObjectName("vsDirectoryEdit")
        self.horizontalLayout_3.addWidget(self.valveSizingDirectoryEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.valveSizingDirectoryButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valveSizingDirectoryButton.sizePolicy().hasHeightForWidth())
        self.valveSizingDirectoryButton.setSizePolicy(sizePolicy)
        self.valveSizingDirectoryButton.setObjectName("vsDirectoryButton")
        self.verticalLayout_2.addWidget(self.valveSizingDirectoryButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("variables")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.variablesTree = QtWidgets.QTreeView(self.tab_2)
        self.variablesTree.setObjectName("variable_tree")
        self.gridLayout_3.addWidget(self.variablesTree, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.expandButton = QtWidgets.QPushButton(self.tab_2)
        self.expandButton.setObjectName("expandButton")
        self.horizontalLayout.addWidget(self.expandButton)
        self.collapseButton = QtWidgets.QPushButton(self.tab_2)
        self.collapseButton.setObjectName("collapseButton")
        self.horizontalLayout.addWidget(self.collapseButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.undoButton = QtWidgets.QPushButton(self.tab_2)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout.addWidget(self.undoButton)
        self.redoButton = QtWidgets.QPushButton(self.tab_2)
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout.addWidget(self.redoButton)
        self.revertButton = QtWidgets.QPushButton(self.tab_2)
        self.revertButton.setObjectName("revertButton")
        self.horizontalLayout.addWidget(self.revertButton)
        # added
        self.horizontalLayout_label = QtWidgets.QHBoxLayout()
        self.horizontalLayout_label.setObjectName("horizontalLayout_label")
        self.label_startup = QtWidgets.QLabel(self.tab_2)
        self.label_startup.setText("Startup File Location:")
        self.horizontalLayout_label.addWidget(self.label_startup)

        self.horizontalLayout_startup = QtWidgets.QHBoxLayout()
        self.horizontalLayout_startup.setObjectName("horizontalLayout_startup")
        self.startupLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.startupLineEdit.setReadOnly(True)
        self.startupLineEdit.setObjectName("startupLineEdit")
        self.localButton = QtWidgets.QPushButton(self.tab_2)
        self.localButton.setObjectName("localButton")
        self.serverButton = QtWidgets.QPushButton(self.tab_2)
        self.serverButton.setObjectName("localButton")
        self.horizontalLayout_startup.addWidget(self.startupLineEdit)
        self.horizontalLayout_startup.addWidget(self.localButton)
        self.horizontalLayout_startup.addWidget(self.serverButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_startup, 1, 0, 1, 1)
        #
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.filterEdit = QtWidgets.QLineEdit(self.tab_2)
        self.filterEdit.setObjectName("filterEdit")
        self.gridLayout_3.addWidget(self.filterEdit, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("themes")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.themeListWidget = QtWidgets.QListWidget(self.tab_3)
        self.themeListWidget.setObjectName("theme_listwidget")

        self.horizontalLayout_4.addWidget(self.themeListWidget)
        scrollArea = QtWidgets.QScrollArea()
        scrollArea.setWidgetResizable(True)
        self.previewLayout = QtWidgets.QGridLayout()
        self.previewLayout.setObjectName("previewLayout")
        self.background = QtWidgets.QLabel()
        self.background.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.previewWidget = QtWidgets.QWidget(scrollArea)
        self.previewWidget.setMinimumSize(QtCore.QSize(400, 200))
        self.previewWidget.setObjectName("previewWidget")
        scrollArea.setWidget(self.previewWidget)
        self.previewLayout.addWidget(self.background, 0, 0, 2, 1)
        self.previewLayout.addWidget(self.previewWidget, 0, 0)
        self.customThemeButton = QtWidgets.QPushButton("Add Custom Theme")
        self.horizontalLayout_4.addWidget(scrollArea)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.customThemeButton, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.undoStack = QtWidgets.QUndoStack()
        self.rootModel = QtGui.QStandardItemModel()
        self.rootModel.setHorizontalHeaderLabels(['Variable', 'Value'])
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.label_3.setText(_translate("Settings", "Previous Working Directories:"))
        self.previousWorkingDirectoryButton.setText(_translate("Settings", "Set Selected Item as Working Directory"))
        self.label.setText(_translate("Settings", "Working Directory:"))
        self.workingDirectoryButton.setText(_translate("Settings", "Choose Directory..."))
        self.label_4.setText(_translate("Settings", "Previous ValveSizing Directories:"))
        self.previousValveSizingButton.setText(_translate("Settings", "Set Selected Item as ValveSizing Directory"))
        self.label_2.setText(_translate("Settings", "Valve Sizing Directory:"))
        self.valveSizingDirectoryButton.setText(_translate("Settings", "Choose Directory..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Directories"))
        self.expandButton.setText(_translate("Settings", "Expand All"))
        self.collapseButton.setText(_translate("Settings", "Collapse All"))
        self.undoButton.setText(_translate("Settings", "Undo"))
        self.redoButton.setText(_translate("Settings", "Redo"))
        self.revertButton.setText(_translate("Settings", "Revert All"))
        self.localButton.setText(_translate("Settings", "Local"))
        self.serverButton.setText(_translate("Settings", "Server"))
        self.filterEdit.setPlaceholderText(
            _translate("Settings", "Type in variable to change. (Variables revert to normal values on program exit.)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Variables"))
        __sortingEnabled = self.themeListWidget.isSortingEnabled()
        self.themeListWidget.setSortingEnabled(False)
        self.themeListWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "Themes"))
